APR-2069 Adding outcome column to applications tab
SkillsFundingAgency/das-roatp-oversight pull request #21
Opened 2021-01-14 10:17 UTC by ConorTill

2021-01-14 10:36 UTC, MarkFCain commented on src/SFA.DAS.RoatpOversight.Domain/ModerationStatus.cs
> +    }
Hi, can you update this class to be:   public class ModerationReviewStatus
    {
        public const string Fail = "Fail";
        public const string Pass = "Pass";
    }

2021-01-14 10:37 UTC, MarkFCain approved these changes

2021-01-14 10:37 UTC, MarkFCain commented on src/SFA.DAS.RoatpOversight.Domain/GatewayReviewStatus.cs
> +    }
Can you update this class to be
public class GatewayReviewStatus
    {
        public const string Fail = "Fail";
        public const string Pass = "Pass";
    }

2021-01-22 10:39 UTC, chrisfoster76 requested changes

2021-01-22 10:39 UTC, chrisfoster76 commented on src/SFA.DAS.RoatpOversight.Web/Views/Oversight/Applications.cshtml
> +                                            bool OutcomePass = application.GatewayReviewStatus == GatewayReviewStatus.Pass
Could we determine the pass/fail status inside a property on the viewmodel, and keep the markup more readable? It'd be unit testable that way, too.

2021-02-03 15:48 UTC, chrisfoster76 requested changes
One comment about a property I think is unused.

2021-02-03 15:48 UTC, chrisfoster76 commented on src/SFA.DAS.RoatpOversight.Domain/ApplicationDetails.cs
> +        public bool OutcomePass => GatewayReviewStatus == Domain.GatewayReviewStatus.Pass
I'm not sure this is used

2021-02-04 09:56 UTC, chrisfoster76 approved these changes

2021-02-04 15:19 UTC, merged